<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BJ-AB055775-T" name="TimeOutTest" tests="2" failures="0" timestamp="2019-02-13T13:51:07 CST" time="4.029" errors="1">
  <testcase name="testSuccess" time="2.010" classname="TimeOutTest"/>
  <testcase name="testFailed" time="2.019" classname="TimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TimeOutTest.testFailed() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TimeOutTest.testFailed() didn't finish within the time-out 2000
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signalAll(AbstractQueuedSynchronizer.java:1953)
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:716)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1014)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testFailed -->
</testsuite> <!-- TimeOutTest -->
